#pragma once

// From glfw.h
#define GINGA_MOUSE_BUTTON_1         0
#define GINGA_MOUSE_BUTTON_2         1
#define GINGA_MOUSE_BUTTON_3         2
#define GINGA_MOUSE_BUTTON_4         3
#define GINGA_MOUSE_BUTTON_5         4
#define GINGA_MOUSE_BUTTON_6         5
#define GINGA_MOUSE_BUTTON_7         6
#define GINGA_MOUSE_BUTTON_8         7
#define GINGA_MOUSE_BUTTON_LAST      GINGA_MOUSE_BUTTON_8
#define GINGA_MOUSE_BUTTON_LEFT      GINGA_MOUSE_BUTTON_1
#define GINGA_MOUSE_BUTTON_RIGHT     GINGA_MOUSE_BUTTON_2
#define GINGA_MOUSE_BUTTON_MIDDLE    GINGA_MOUSE_BUTTON_3